// Embed a Resumex identity fingerprint into a compiled PDF buffer.
//
// Two complementary layers of fingerprinting are applied:
//
//   1. Document Info dictionary  — Producer / Creator / Keywords fields that
//      any PDF viewer (Acrobat, Preview, pdfinfo, etc.) can read.
//
//   2. XMP metadata stream       — the same fields in standard XMP so that
//      metadata-aware search engines, DRM tools, and forensic tools pick them
//      up even if the Info dict is stripped.
//
// The marker token is:  RESUMEX-<YYYY>-<build-hash>
// where <build-hash> is the first 8 chars of the SHA-256 of the PDF content
// BEFORE fingerprinting.  This makes each PDF uniquely traceable back to its
// source compile without storing anything server-side.

import * as mupdf from 'mupdf';
import { createHash } from 'node:crypto';

const SITE_NAME = 'ResumeX';
const PRODUCER = `${SITE_NAME} PDF Engine`;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/** SHA-256 hex of a Buffer, truncated to `len` chars. */
function contentHash(buf, len = 8) {
  return createHash('sha256').update(buf).digest('hex').slice(0, len).toUpperCase();
}

/** Build the fingerprint token string. */
function buildToken(buf) {
  const year = new Date().getFullYear();
  const hash = contentHash(buf);
  return `RESUMEX-${year}-${hash}`;
}

/** ISO-8601 timestamp (without ms). */
function isoNow() {
  return new Date().toISOString().replace(/\.\d{3}Z$/, 'Z');
}

/** Minimal XMP packet embedding Producer, Creator, and Keywords. */
function buildXmp(token) {
  const now = isoNow();
  return `<?xpacket begin='\uFEFF' id='W5M0MpCehiHzreSzNTczkc9d'?>
<x:xmpmeta xmlns:x="adobe:ns:meta/">
  <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
    <rdf:Description rdf:about=""
        xmlns:pdf="http://ns.adobe.com/pdf/1.3/"
        xmlns:xmp="http://ns.adobe.com/xap/1.0/"
        xmlns:dc="http://purl.org/dc/elements/1.1/">
      <pdf:Producer>${PRODUCER}</pdf:Producer>
      <pdf:Keywords>${SITE_NAME} resume-builder ${token}</pdf:Keywords>
      <xmp:CreatorTool>${SITE_NAME}</xmp:CreatorTool>
      <xmp:CreateDate>${now}</xmp:CreateDate>
      <xmp:ModifyDate>${now}</xmp:ModifyDate>
      <dc:creator><rdf:Seq><rdf:li>${SITE_NAME}</rdf:li></rdf:Seq></dc:creator>
    </rdf:Description>
  </rdf:RDF>
</x:xmpmeta>
<?xpacket end='w'?>`;
}

// ---------------------------------------------------------------------------
// Main export
// ---------------------------------------------------------------------------

/**
 * Embed a Resumex fingerprint into `pdfBuffer` and return a new Buffer.
 * Never throws — if anything goes wrong the original buffer is returned.
 *
 * @param {Buffer} pdfBuffer  The compiled (and optionally trimmed) PDF bytes.
 * @returns {Buffer}
 */
export function fingerprintPdf(pdfBuffer) {
  try {
    const token = buildToken(pdfBuffer);
    const doc = mupdf.Document.openDocument(pdfBuffer, 'application/pdf');

    // ------------------------------------------------------------------
    // 1. Document Info dictionary
    // ------------------------------------------------------------------
    doc.setMetaData('info:Producer', PRODUCER);
    doc.setMetaData('info:Creator', SITE_NAME);
    doc.setMetaData('info:Keywords', `${SITE_NAME} resume-builder ${token}`);
    doc.setMetaData('info:Subject', `Resume generated by ${SITE_NAME}`);

    // ------------------------------------------------------------------
    // 2. XMP metadata stream
    // ------------------------------------------------------------------
    try {
      doc.setMetaData('xml:metadata', buildXmp(token));
    } catch {
      // setMetaData for XMP may not be available in all mupdf builds — skip.
    }



    // ------------------------------------------------------------------
    // Serialise
    // ------------------------------------------------------------------
    const out = doc.saveToBuffer('');
    return Buffer.from(out.asUint8Array());
  } catch (err) {
    // Fingerprinting must never break a successful compile.
    console.warn('[fingerprint] skipped:', err.message);
    return pdfBuffer;
  }
}
