// SQLite connection + Drizzle instance. Migrations (generated by drizzle-kit into
// ./drizzle) are applied automatically on first import, so a fresh clone spins up
// a ready database with no manual migrate step.

import path from 'node:path';
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';
import Database from 'better-sqlite3';
import { drizzle } from 'drizzle-orm/better-sqlite3';
import { migrate } from 'drizzle-orm/better-sqlite3/migrator';
import * as schema from './schema.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const DB_PATH = process.env.DATABASE_URL
  ? path.resolve(process.env.DATABASE_URL)
  : path.resolve(__dirname, '../../data/resumex.db');

// Ensure the data directory exists (gitignored).
fs.mkdirSync(path.dirname(DB_PATH), { recursive: true });

const sqlite = new Database(DB_PATH);
sqlite.pragma('journal_mode = WAL'); // better concurrency for the dev server
sqlite.pragma('foreign_keys = ON'); // enforce cascade deletes

export const db = drizzle(sqlite, { schema });

let migrated = false;

// Apply pending migrations. Called once from server bootstrap before serving.
export function runMigrations() {
  if (migrated) return;
  const migrationsFolder = path.resolve(__dirname, '../../drizzle');
  migrate(db, { migrationsFolder });
  migrated = true;
  console.log(`[db] ready at ${DB_PATH}`);
}

export { schema };
